###
GET http://localhost:8080/api/users


###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "first_name": "Emiliano",
    "last_name": "Larroca",
    "email": "e@gmail.com"
}

###
PUT http://localhost:8080/api/users/657fc7163eade5e1e2396c59
Content-Type: application/json

{
    "first_name": "Emi",
    "last_name": "Larroca",
    "email": "emiliano@gmail.com"
}

###
DELETE http://localhost:8080/api/users/657fc7163eade5e1e2396c59
Content-Type: application/json



//PRODUCTS

###
GET http://localhost:8080/api/products

###
GET http://localhost:8080/api/products/65d3fa49ff88d2b237ddfb6e


###
POST http://localhost:8080/api/products
Content-Type:  application/json

{
    "title": "producto2",
    "price": 50,
    "category": "verdura",
    "stock": 5,
    "thumbnail": "imagen2",
    "IsActive": "true"
}

###
POST http://localhost:8080/api/carts
Content-Type: : application/json

{
    "products": [{"product": "658267cec06f43584aa0d9c6"}, {"product": "65826bd4c3db4deeaf7cedfe",}]
}

###
GET http://localhost:8080/api/carts/659df1782f8baeb102cf50e4


###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "emi@emi2.com.ar",
    "password": "1234"
}


###
GET http://localhost:8080/api/sessions/current
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJfaWQiOiI2NWIxN2ZlMmQ0ZWM1NDVjYjM1MGE1ZmQiLCJmaXJzdF9uYW1lIjoiZWVlIiwibGFzdF9uYW1lIjoiZWVlIiwiZW1haWwiOiJlQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDhTYm14RXZnZFczVzVqa3FScHcwNXVkeDJzazNaVVZudXRFZWY0Qlc3YXNzcFExWjA0QjMyIiwicm9sZSI6InVzZXIiLCJfX3YiOjB9LCJyb2xlIjoidXNlciIsImlhdCI6MTcwNjEzMTYzOCwiZXhwIjoxNzA2MjE4MDM4fQ.aYzrztpXKUil-3yYEti5XqNFuSgZwCm0QOjj3RHZaJI